name: TCPlugin
version: @version@
main: org.qrl.tcplugin.TCPlugin
api-version: 1.20
authors: [ LaSpruca ]
depend: [ AdvancedBan ]
description: The official TCPlugin
website: https://qrl.nz
commands:
  givebaton:
    usage: /givebaton [player]
    description: Gives a player a TCPD baton, brrr
  discord:
    usage: /discord
    description: Gives you the Technocraft Discord Information
  bee:
    usage: According to all known laws of aviation, there is no way that a bee should be able to fly.
    description: According to all known laws of aviation, there is no way that a bee should be able to fly.
